---
title: "Check eta"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#--------------------------------
#  This file is used to
#  1.check eta2, eta3 and eta4
#  Last updated date: 7/11/2017
#--------------------------------
```

```{r, include=FALSE}
setwd("/Users/peterwang/Desktop/Research/missingdata/Project/code/debug")
source("data.generation.R")
```

```{r}
##set parameters
eta=eta_sim  ##iterate from true values of eta
v=v_sim
beta=beta_sim
M=M_sim
sgmr2=sgmr2_sim
sgm2=sgm2_sim
E=E_sim
c=c_sim
b=b_sim
e=e_sim
X=X_sim    ##rename the simulated compelete X_{it}

##number of iterations
n_iter=10000         

##recording structure
eta_keep=matrix(0, nrow=n_iter, ncol=K)  

PG_eta=matrix(0, n, K-1)    ## for w_{il} in updating eta_{l}
k_eta=matrix(0, n, K-1)     ## for k_{l} in updating eta_{l}

for (m in 1:n_iter){  

  ##sample eta2, eta3 and eta4
  for(l in 2:K){
    for(i in 1:n){
      tilting_eta=V_sim[i]*eta[l]-log(sum(exp(V_sim[i]*eta[-l])) )
      PG_eta[i,l-1]=rpg(num=1, h=1, z=tilting_eta)
      index_eta=ifelse(c[i]==l,1,0)
      k_eta[i,l-1]=index_eta-1/2+PG_eta[i,l-1]*log(sum(exp(V_sim[i]*eta[-l])))
    }
    S_eta=(1/eta_pri+t(V_sim)%*%diag(PG_eta[,l-1])%*%V_sim)^{-1}
    m_eta=S_eta*t(V_sim)%*%k_eta[,l-1]
    eta[l]=rnorm(n=1,mean=m_eta, sd=sqrt(S_eta))
  }
  
  eta_keep[m,]=eta
}

burnin=5000
traceplot(x=as.mcmc(eta_keep[-(1:burnin),2]), ylab="eta_2")
traceplot(x=as.mcmc(eta_keep[-(1:burnin),3]), ylab="eta_3")
traceplot(x=as.mcmc(eta_keep[-(1:burnin),4]), ylab="eta_4")


```

