---
title: "Check Beta"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#--------------------------------
#  This file is used to
#  1.check beta
#  Last updated date: 7/11/2017
#--------------------------------
```

```{r, include=FALSE}
setwd("/Users/peterwang/Desktop/Research/missingdata/Project/code/debug")
source("data.generation.R")
```

```{r}
##set other parameters equal their true values
eta=eta_sim
v=v_sim
M=M_sim
sgmr2=sgmr2_sim
sgm2=sgm2_sim
E=E_sim
c=c_sim
b=b_sim
e=e_sim
X=X_sim    ##rename the simulated compelete data X_{it}

##sample beta from its posterior distribution
var_beta=solve((1/beta_pri)*diag(2)+(1/sgm2)*sum_D)
sum_beta=rep(0, 2)
for (i in 1:n){
  sum_beta=sum_beta+t(D[1:T[i],c(2*i-1, 2*i)])%*%(X[1:T[i], i]-D_star[1:T[i],i]*M[c[i]]-D_dstar[1:T[i],i]*b[i])
}
mean_beta=(1/sgm2)*var_beta%*%sum_beta
beta=mvrnorm(n=1000, mu=mean_beta, Sigma = var_beta)
posterior.mean.beta=c(mean(beta[,1]), mean(beta[,2]))
posterior.mean.beta

##traceplot  
traceplot(x=as.mcmc(beta[ ,1]), ylab="beta_1")
traceplot(x=as.mcmc(beta[ ,2]), ylab="beta_2")

```

