---
title: "Check sgm2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#--------------------------------
#  This file is used to
#  1.check sigma^{2}
#  Last updated date: 7/11/2017
#--------------------------------
```

```{r, include=FALSE}
setwd("/Users/peterwang/Desktop/Research/missingdata/Project/code/debug")
source("data.generation.R")
```

```{r}
##set other parameters equal their true values
eta=eta_sim
v=v_sim
M=M_sim
beta=beta_sim
sgmr2=sgmr2_sim
E=E_sim
c=c_sim
b=b_sim
e=e_sim
X=X_sim    ##rename the simulated compelete data X_{it}

##sample sgm2
Big.beta=matrix(0, 2*n, n)
for (i in 1:n){
  Big.beta[c(2*i-1, 2*i),i]=beta
}
Big.M=diag(M[c])
Big.b=diag(b)
Big.sgm2=X-D%*%Big.beta-D_star%*%Big.M-D_dstar%*%Big.b

shape_sgm2=(1/2)*sum(T)+sgm2_pri
scale_sgm2=(1/2)*sum(Big.sgm2^{2})+sgm2_pri
sgm2=rigamma(n=1000, a=shape_sgm2, b=scale_sgm2)

##histogram and traceplot  
histogram(sgm2)
traceplot(x=as.mcmc(sgm2), ylab="sgm2")

```

