---
title: "Linear mixed effects model(no mixture components)"
date: "7/18/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE}
rm(list=ls())
set.seed(0311)
library(MASS) ##use function mvrnorm
library(LaplacesDemon) ##use function rcat
library(MCMCpack) ##use function rinvgamma, default rate=1
library(mvtnorm)  ##use function dmvnorm, rmvt
library(pscl)  ##use function rigamma 
#library(metRology)  ##use function rt.scaled 
library(BayesLogit) ##use rpg
library(coda)
library(LearnBayes)
#library(doParallel)
```


```{r}
lmm=function(sgmr2sim, sgm2sim, sgmr2ini, sgm2ini){
#---------------------------------
#      Global set-up       
#---------------------------------
n=100 ##number of subject

##assign each subject the number of tracked quarters
T=sample(5:40, size=n, replace=TRUE) 

#--------------------------------------
#   Complete simulated data generation
#--------------------------------------
##set up true values of parameters
beta_sim=c(-0.4, 0.5)
sgmr2_sim=sgmr2sim               ##true value of variance of b_{i}
sgm2_sim=sgm2sim                ##true value of variance of epsilon_{it}

##generate time-invariate covariate V_{i}
V_sim=rnorm(n=n, mean=0, sd=1)

##generate random effect b_{i}
b_sim=rnorm(n,mean=0, sd=sqrt(sgmr2_sim))  

##set D_{i} and D^{**}_{i}
D=matrix(0, sum(T), 2)
D[,1]=rep(1,sum(T))
D[,2]=rep(V_sim,T)

D_dstar=rep(1, sum(T))

##simulate X_{it}
Bigb=rep(b_sim, T)
X_sim=D%*%beta_sim+D_dstar*Bigb+rnorm(n=sum(T), mean=0, sd=sqrt(sgm2_sim))

#------------
# PRIORS    
#------------
beta_pri=10^{4} 
sgm2_pri=0.001
sgmr2_pri=0.001

#------------------------
# SET INITIAL VALUES
#------------------------
inits=list(beta=c(-0.5, 0.8),
           sgmr2=sgmr2ini,
           sgm2=sgm2ini, 
           b=rnorm(n, mean=0, sd=sqrt(sgmr2ini))     ##initial value of random effect b_{i}
)

#-----------------------
#   SET-UP OF ITERATION                       
#-----------------------
#number of iterations
n_iter=5000

##variable names in the iteration
beta=inits$beta
sgmr2=inits$sgmr2
sgm2=inits$sgm2
b=inits$b
X=X_sim

##recording structure, each row is one iteration
beta_keep=matrix(0, nrow=n_iter, ncol=2)  
sgmr2_keep=rep(0, n_iter)  
sgm2_keep=rep(0, n_iter)   
b_keep=matrix(0, nrow=n_iter, ncol=n) 

crossD=crossprod(D)         ## t(D)%*%D for updating beta

#------------------
# RUN ITERATIONS
#------------------
for (m in 1:n_iter){  
  
  ##sample beta
  Bigb=rep(b, T)
  sum_beta=crossprod(D, X-D_dstar*Bigb)
  var_beta=solve((1/beta_pri)*diag(2)+(1/sgm2)*crossD)
  mean_beta=(1/sgm2)*(var_beta%*%sum_beta)
  beta=mvrnorm(n=1, mu=mean_beta, Sigma = var_beta)
  
  ##sample b[i]
  for (i in 1:n){
    b_index=c(rep(0,i-1),1,rep(0, n-i))
    var_b=((1/sgmr2)+(1/sgm2)*T[i])^{-1}
    mean_b=(1/sgm2)*var_b*sum((X-D%*%beta)*rep(b_index,T))
    b[i]=rnorm(1, mean=mean_b, sd=sqrt(var_b))
  }  
  
  ##sample sigma_{r}^{2}
  sgmr2=rigamma(n=1, a=(n/2)+sgmr2_pri, b=(1/2)*sum(b^{2})+sgmr2_pri) 
  
  ##sample sigma^{2}
  Bigb=rep(b,T)
  sum_sgm2=sum((X-D%*%beta-D_dstar*Bigb)^2)
  shape_sgm2=(1/2)*sum(T)+sgm2_pri
  scale_sgm2=(1/2)*sum_sgm2+sgm2_pri
  sgm2=rigamma(n=1, a=shape_sgm2, b=scale_sgm2)
  

  ##record parameters
  beta_keep[m, ]=beta
  b_keep[m, ]=b
  sgmr2_keep[m]=sgmr2
  sgm2_keep[m]=sgm2

} ##iteration ends

burnin=2000
##posterior mean
posterior.mean.beta=apply(beta_keep[-(1:burnin),],2, mean)
posterior.mean.sgmr2=mean(sgmr2_keep[-(1:burnin)])
posterior.mean.sgm2=mean(sgm2_keep[-(1:burnin)])

traceplot(x=as.mcmc(beta_keep[-(1:burnin),1]), ylab="beta_1")
traceplot(x=as.mcmc(beta_keep[-(1:burnin),2]), ylab="beta_2")
traceplot(x=as.mcmc(sgmr2_keep[-(1:burnin)]), ylab="sgmr2")
traceplot(x=as.mcmc(sgm2_keep[-(1:burnin)]), ylab="sgm2")
return(list(PMbeta=posterior.mean.beta, PMsgmr2=posterior.mean.sgmr2, PMsgm2=posterior.mean.sgm2))
} ##function ends

```

```{r}
mod1=lmm(sgmr2sim = 1, sgm2sim = 1, sgmr2ini = 1.5^{2}, sgm2ini = 1.5^{2})
mod1$PMbeta
mod1$PMsgmr2
mod1$PMsgm2
```

```{r}
mod2=lmm(sgmr2sim = 10, sgm2sim = 5, sgmr2ini = 15, sgm2ini = 10)
mod2$PMbeta
mod2$PMsgmr2
mod2$PMsgm2
```

```{r}
mod3=lmm(sgmr2sim = 5, sgm2sim = 10, sgmr2ini = 10, sgm2ini = 15)
mod3$PMbeta
mod3$PMsgmr2
mod3$PMsgm2
```




















